apiVersion: apps/v1
kind: Deployment
metadata:
  name: forest-cover-backend
  labels:
    app: forest-cover
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forest-cover
      component: backend
  template:
    metadata:
      labels:
        app: forest-cover
        component: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/karthik-ak-git/forest_cover_prediction:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: forest-cover-secrets
              key: database-url
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: forest-cover-secrets
              key: secret-key
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: models
          mountPath: /app/models
          readOnly: true
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: forest-cover-backend-service
  labels:
    app: forest-cover
    component: backend
spec:
  selector:
    app: forest-cover
    component: backend
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: forest-cover-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: forest-cover-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
